title: Cool Bot Pizza

home: /index.html
menu: /menu.html
location: /location.html
about: /about.html
contact: /contact.html
blogLink: /#
twit: https://twitter.com/billbunkum

collections: 
  reviews:
    output: true